#!/usr/bin/env python3
"""
Test script to verify audit logs endpoint works with JWT fix
"""

import requests
import json
import sys

def test_audit_logs_endpoint():
    """Test that audit logs endpoint works with development token"""

    # Development token generated by the frontend
    dev_token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMDE3NTAxODA1MDA4MzY4MDMwNjkiLCJlbWFpbCI6Indpc2VybHlAZ21haWwuY29tIiwibmFtZSI6Indpc2VybHkgd29uZyIsInJvbGUiOiJhZG1pbiIsIm9yZ2FuaXphdGlvbiI6IksyTGFiIiwiaWF0IjoxNzI2ODI1ODI0LCJleHAiOjE3MjY5MTIyMjQsImlzcyI6InByb21wdG9wcy1kZXYiLCJhdWQiOiJwcm9tcHRvcHMtd2ViIn0.dev-signature-not-for-production"

    # Test audit logs endpoint
    base_url = "http://localhost:8000"
    headers = {
        "Authorization": f"Bearer {dev_token}",
        "Content-Type": "application/json"
    }

    print("=== Testing Audit Logs Endpoint ===")

    try:
        # Test audit logs endpoint
        response = requests.get(f"{base_url}/api/v1/governance/audit-logs", headers=headers, timeout=10)

        print(f"Status Code: {response.status_code}")
        print(f"Response Headers: {dict(response.headers)}")

        if response.status_code == 200:
            print("✅ SUCCESS: Audit logs endpoint working!")
            try:
                data = response.json()
                print(f"Response: {json.dumps(data, indent=2)}")
            except:
                print(f"Raw Response: {response.text}")
        elif response.status_code == 401:
            print("❌ FAILED: Still getting 401 Unauthorized")
            print(f"Response: {response.text}")
        else:
            print(f"⚠️  Unexpected status code: {response.status_code}")
            print(f"Response: {response.text}")

    except requests.exceptions.ConnectionError:
        print("❌ Connection Error: Make sure the backend server is running on port 8000")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Error: {e}")

    print("\n=== Testing Approval Flows Endpoint (for comparison) ===")

    try:
        # Test approval flows endpoint (this was working before)
        response = requests.get(f"{base_url}/v1/approval-flows", headers=headers, timeout=10)

        print(f"Status Code: {response.status_code}")

        if response.status_code == 200:
            print("✅ SUCCESS: Approval flows endpoint working!")
        elif response.status_code == 401:
            print("❌ FAILED: Approval flows endpoint also failing")
        else:
            print(f"⚠️  Unexpected status code: {response.status_code}")

    except Exception as e:
        print(f"❌ Error testing approval flows: {e}")

if __name__ == "__main__":
    test_audit_logs_endpoint()