"""Add missing columns to prompts table

Revision ID: 0400fbf655ca
Revises: 31b3c3054a91
Create Date: 2025-09-13 18:58:37.572714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0400fbf655ca'
down_revision: Union[str, None] = '31b3c3054a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('name', sa.String(), nullable=False))
    op.add_column('prompts', sa.Column('target_models', sa.JSON(), nullable=False))
    op.add_column('prompts', sa.Column('model_specific_prompts', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompts', 'model_specific_prompts')
    op.drop_column('prompts', 'target_models')
    op.drop_column('prompts', 'name')
    # ### end Alembic commands ###
