"""add_promptops_v1_models_fixed

Revision ID: 31b3c3054a91
Revises: 5b5bdbdca9bd
Create Date: 2025-09-13 11:00:26.214038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31b3c3054a91'
down_revision: Union[str, None] = '5b5bdbdca9bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # Update modules table to add project_id and timestamp columns
    op.add_column('modules', sa.Column('project_id', sa.String(), nullable=True))
    op.add_column('modules', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('modules', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))

    # Add foreign key constraint for modules.project_id
    op.create_foreign_key('fk_modules_project_id', 'modules', 'projects', ['project_id'], ['id'])

    # Set default project_id for existing modules and make it non-nullable
    op.execute("INSERT INTO projects (id, name, owner) VALUES ('default-project', 'Default Project', 'system')")
    op.execute("UPDATE modules SET project_id = 'default-project' WHERE project_id IS NULL")
    op.alter_column('modules', 'project_id', nullable=False)

    # Add unique constraint on modules.id to allow foreign key references
    op.create_unique_constraint('uq_modules_id', 'modules', ['id'])

    # Create prompts table with foreign key reference
    op.create_table('prompts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('mas_intent', sa.String(), nullable=False),
    sa.Column('mas_fairness_notes', sa.String(), nullable=False),
    sa.Column('mas_testing_notes', sa.String(), nullable=True),
    sa.Column('mas_risk_level', sa.String(), nullable=False),
    sa.Column('mas_approval_log', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name='fk_prompts_module_id'),
    sa.PrimaryKeyConstraint('id', 'version')
    )

    # Add unique constraint on prompts.id to allow foreign key references
    op.create_unique_constraint('uq_prompts_id', 'prompts', ['id'])

    op.create_table('approval_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('approver', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name='fk_approval_requests_prompt_id'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('model_compatibilities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('prompt_id', sa.String(), nullable=False),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('model_provider', sa.String(), nullable=False),
    sa.Column('is_compatible', sa.Boolean(), nullable=False),
    sa.Column('compatibility_notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], name='fk_model_compatibilities_prompt_id'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_foreign_key('fk_aliases_template_version', 'aliases', 'templates', ['template_id', 'target_version'], ['id', 'version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_aliases_template_version', 'aliases', type_='foreignkey')
    op.drop_constraint('fk_model_compatibilities_prompt_id', 'model_compatibilities', type_='foreignkey')
    op.drop_table('model_compatibilities')
    op.drop_constraint('fk_approval_requests_prompt_id', 'approval_requests', type_='foreignkey')
    op.drop_table('approval_requests')
    op.drop_constraint('uq_prompts_id', 'prompts', type_='unique')
    op.drop_constraint('fk_prompts_module_id', 'prompts', type_='foreignkey')
    op.drop_table('prompts')
    op.drop_constraint('uq_modules_id', 'modules', type_='unique')
    op.drop_constraint('fk_modules_project_id', 'modules', type_='foreignkey')
    op.alter_column('modules', 'project_id', nullable=True)
    op.drop_column('modules', 'updated_at')
    op.drop_column('modules', 'created_at')
    op.drop_column('modules', 'project_id')
    op.execute("DELETE FROM projects WHERE id = 'default-project'")
    op.drop_table('projects')
    # ### end Alembic commands ###
