"""add api_key and secret_key fields to client_api_keys for decrypted display

Revision ID: 43eefcc5fa83
Revises: f6f12baf64d4
Create Date: 2025-09-14 02:30:29.899191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43eefcc5fa83'
down_revision: Union[str, None] = 'f6f12baf64d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_api_keys', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('client_api_keys', sa.Column('secret_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_api_keys', 'secret_key')
    op.drop_column('client_api_keys', 'api_key')
    # ### end Alembic commands ###
