"""remove redundant api_key and secret_key fields from client_api_keys

Revision ID: 4a8b2c3d4e5f
Revises: 43eefcc5fa83
Create Date: 2025-09-14 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8b2c3d4e5f'
down_revision: Union[str, None] = '43eefcc5fa83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove redundant api_key and secret_key fields
    op.drop_column('client_api_keys', 'api_key')
    op.drop_column('client_api_keys', 'secret_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the fields for rollback
    op.add_column('client_api_keys', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('client_api_keys', sa.Column('secret_key', sa.String(), nullable=True))
    # ### end Alembic commands ###