"""Initial migration

Revision ID: 5012a6b7d143
Revises: 
Create Date: 2025-09-12 21:39:16.163771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5012a6b7d143'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('alias', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('target_version', sa.String(), nullable=False),
    sa.Column('weights_json', sa.JSON(), nullable=True),
    sa.Column('etag', sa.String(), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('alias')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('ts', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('suite_id', sa.String(), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('slot', sa.String(), nullable=False),
    sa.Column('render_body', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('hash', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', 'version')
    )
    op.create_table('tenant_overlays',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('overrides_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id', 'template_id', 'version')
    )
    op.create_table('variants',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('overlay_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('template_id', 'name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('variants')
    op.drop_table('tenant_overlays')
    op.drop_table('templates')
    op.drop_table('policies')
    op.drop_table('modules')
    op.drop_table('evaluation_runs')
    op.drop_table('audit_logs')
    op.drop_table('aliases')
    # ### end Alembic commands ###
