"""Add OAuth support to User model

Revision ID: 5b5bdbdca9bd
Revises: 5012a6b7d143
Create Date: 2025-09-12 23:24:48.057782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b5bdbdca9bd'
down_revision: Union[str, None] = '5012a6b7d143'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
