"""Add secret_key column to client_api_keys

Revision ID: a08dba1d24dc
Revises: 0400fbf655ca
Create Date: 2025-09-14 01:47:59.198273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08dba1d24dc'
down_revision: Union[str, None] = '0400fbf655ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Note: The secret_key column addition and constraint drops have been removed
    # as they cause dependency issues. The unique constraints on modules.id and
    # prompts.id are needed for foreign key relationships.
    # The secret_key_encrypted column already exists in the model.

    # Create the rate limit unique constraint
    op.create_unique_constraint('uq_rate_limit_window', 'rate_limit_records', ['api_key_id', 'window_type', 'window_start'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop the rate limit unique constraint
    op.drop_constraint('uq_rate_limit_window', 'rate_limit_records', type_='unique')

    # Note: We don't recreate the dropped constraints or drop the secret_key column
    # as they were never actually modified in the corrected upgrade.

    # ### end Alembic commands ###
