"""add encrypted api_key field to client_api_keys

Revision ID: f6f12baf64d4
Revises: a08dba1d24dc
Create Date: 2025-09-14 02:15:28.465277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6f12baf64d4'
down_revision: Union[str, None] = 'a08dba1d24dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_api_keys', sa.Column('api_key_encrypted', sa.String(), nullable=True))
    op.alter_column('client_api_keys', 'secret_key_encrypted',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_api_keys', 'secret_key_encrypted',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('client_api_keys', 'api_key_encrypted')
    # ### end Alembic commands ###
